# https://help.github.com/en/github/administering-a-repository/configuration-options-for-dependency-updates#about-the-dependabotyml-file
version: 2
updates:
  - package-ecosystem: composer
    directory: /
    schedule:
      interval: daily
    reviewers:
      - cs278
    commit-message:
      prefix: composer
      include: scope
    labels: []
  - package-ecosystem: npm
    directory: /
    schedule:
      interval: monthly
    reviewers:
      - cs278
    commit-message:
      prefix: npm
      include: scope
    labels: []
