services:
    app.about_controller:
        class: AppBundle\Controller\AboutController
        arguments:
            - '@templating'
    app.cv_controller:
        class: AppBundle\Controller\CvController
        arguments:
            - '@templating'
