services:
    app.about_controller:
        class: AppBundle\Controller\AboutController
        arguments:
            - '@templating'
    app.cv_controller:
        class: AppBundle\Controller\CvController
        arguments:
            - '@templating'

    app.inline_markdown_extension:
        class: AppBundle\Twig\InlineMarkdownExtension
        public: false
        tags:
            - { name: twig.extension }

    # app.commonmark_twig_extension:
    #     class: Aptoma\Twig\Extension\MarkdownExtension
    #     arguments:
    #         - '@app.commonmark_adapter'
    #     public: false
    #     tags:
    #         - { name: twig.extension }
    #
    # app.commonmark_adapter:
    #     class: Aptoma\Twig\Extension\MarkdownEngine\PHPLeagueCommonMarkEngine
    #     public: false
