imports:
    - { resource: security.yml }
    - { resource: services.yml }

framework:
    secret:          "%env(APP_SECRET)%"
    router:
        utf8: true
        strict_requirements: ~
    form:            ~
    csrf_protection: ~
    validation:      { enable_annotations: true }
    default_locale:  "en_GB"
    session:
        # handler_id set to null will use default session handler from php.ini
        handler_id:  ~
        save_path:   "%kernel.project_dir%/var/sessions/%kernel.environment%"
    http_method_override: true
    assets:
        json_manifest_path: '%kernel.project_dir%/web/assets/manifest.json'

webpack_encore:
    output_path: '%kernel.project_dir%/web/assets'

# Twig Configuration
twig:
    default_path: "%kernel.project_dir%/templates"
    debug: "%kernel.debug%"
    strict_variables: "%kernel.debug%"
