services:
    app.about_controller:
        class: AppBundle\Controller\AboutController
        arguments:
            - '@templating'
    app.cv_controller:
        class: AppBundle\Controller\CvController
        arguments:
            - '@templating'

    app.inline_markdown_extension:
        class: AppBundle\Twig\InlineMarkdownExtension
        public: false
        tags:
            - { name: twig.extension }
