services:
    App\Controller\:
        resource: '../src/Controller/*'
        public: true
        autowire: true
        autoconfigure: true

    App\Twig\InlineMarkdownExtension:
        public: false
        autoconfigure: true
