services:
    AppBundle\Controller\:
        resource: '../src/AppBundle/Controller/*'
        public: true
        autowire: true
        autoconfigure: true

    AppBundle\Twig\InlineMarkdownExtension:
        public: false
        autoconfigure: true
