name: Composer Rich Diff

on:
  pull_request:

permissions:
    contents: read
    pull-requests: write

jobs:
  diff:
    name: Generate Diff
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: cs278/composer-rich-diff-action@v1
        with:
          path: composer.json
